spring:
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          min-idle: 1
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 启用服务发现
          lower-case-service-id: true
      default-filters:
        # 令牌中继
        - TokenRelay=
      routes:
        - id: 认证中心
          uri: lb://chiot-authentication
          predicates:
            - Path=/chiot-authentication/**
          filters:
            - StripPrefix=1
        - id: 系统服务
          uri: lb://chiot-system
          predicates:
            - Path=/chiot-system/**
          filters:
            - StripPrefix=1
      globalcors:
        corsConfigurations:
          '[/**]': # 对所有路由应用CORS配置
            # 允许所有域名的请求
            allowedOriginPatterns: "*"
            # 允许所有请求方法，如GET、POST、PUT、DELETE等
            allowedMethods: "*"
            # 允许所有请求头
            allowedHeaders: "*"
            # 允许凭证，如Cookies和HTTP认证
            allowCredentials: true
            maxAge: 3600

feign:
  httpclient:
    enabled: true
  okhttp:
    enabled: false
  sentinel: # 开启feign对sentinel的支持
    enabled: false

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: null # 逻辑已删除值
      logic-not-delete-value: now() # 逻辑未删除值
  configuration:
    # 驼峰下划线转换
    map-underscore-to-camel-case: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: org.apache.ibatis.type.EnumOrdinalTypeHandler

security:
  black-path-list:
    # 获取用户认证信息
    - /chiot-system/api/{v}/users/{username}/authInfo